// White-label brand config — edit this file to rebrand the LMS
// Generated by the Worker-Bee white-label builder from vericorecg.com

import type { ThemeId } from './themes'

export interface Brand {
  name: string           // Platform name shown in nav
  tagline: string        // Subtitle on login card
  company: string        // Full legal/display company name
  logoPath: string       // Path under /public or full URL
  logoAlt: string
  defaultTheme: ThemeId  // Theme applied before user picks one
  accentColor: string    // Matches --accent for raw CSS contexts
  contactEmail: string
  website: string
  industry: string       // Used for compliance module selection
}

const brand: Brand = {
  name:         'LMS Core',
  tagline:      'Professional compliance training — built for teams that can\'t afford gaps.',
  company:      'LMS Core',
  logoPath:     '',
  logoAlt:      'LMS Core',
  defaultTheme: 'midnight',
  accentColor:  '#4f46e5',
  contactEmail: 'admin@lmscore.app',
  website:      'https://lms-core.vercel.app',
  industry:     'healthcare-compliance',
}

export default brand
